server:
  port: 8088

spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/project?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 15
      # 最大连接数
      max-active: 30
      # 超时时间(以秒数为单位)
      remove-abandoned-timeout: 180
      # 获取连接超时时间
      max-wait: 3000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

# MyBatis-Plus
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-dev.xml

# swagger
swagger:
  enable: true

# ip地址本地解析
ip:
  local-parsing: true

# 登录
login:
  # 是否限制单用户登录
  single-login: false
  # redis缓存用户过期时间（秒）
  user-cache:
    idle-time: 7200
  # 登录验证码
  login-code:
    # 验证码类型
    code-type: arithmetic
    # 有效期（分钟）
    expiration: 1
    # 宽度
    width: 111
    # 高度
    height: 36
    # 内容长度（默认2位）
    length: 2
    # 字体（为空使用默认值）
    font-name:
    # 字体大小
    font-size: 25

# jwt
jwt:
  header: Authorization
  # token前缀
  token-start-with: Bearer
  # 88位Base64编码
  base64-secret: b2hzZG9maWpzb2RmanNsa2FkZmpvbHNqMDk4MjM0bGtqMmwzaDRtMjNuNGpraDEyazNqaDEyazNoMzQ1MzRqaGpoMjM0MjM0NTZpOWZkbGtqZmxpaWpr
  # 令牌过期时间（秒）默认4小时
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token续期检查间隔时间（毫秒）
  detect: 1800000
  # 续期时间（毫秒）默认半小时
  renew: 3600000

# OSS
oss:
  minio:
    endpoint: http://192.168.123.88:9000
    bucket: project
    access-key: admin
    secret-key: 12345678